import { z } from 'zod';
import { jsonResult } from './_format.js';
import * as core from '../core/data.js';

export function registerDataTools(server) {
  server.tool(
    'po_candles',
    'Get OHLC candle data for an asset. Use summary=true for a compact stats view instead of all bars.',
    {
      asset: z.string().describe('Asset symbol, e.g. EURUSD or EURUSD_otc'),
      limit: z.coerce.number().min(1).max(1000).optional().default(100).describe('Number of candles (default 100)'),
      summary: z.coerce.boolean().optional().default(false).describe('Return summary stats instead of full bar list'),
    },
    async ({ asset, limit, summary }) => {
      try { return jsonResult(core.getCandles(asset, limit, summary)); }
      catch (err) { return jsonResult({ success: false, error: err.message }, true); }
    }
  );

  server.tool(
    'po_prices',
    'Get latest real-time price(s). Pass asset for a single asset, or omit to get latest price for all tracked assets.',
    {
      asset: z.string().optional().describe('Asset symbol (omit for all assets)'),
    },
    async ({ asset }) => {
      try { return jsonResult(core.getPrices(asset || null)); }
      catch (err) { return jsonResult({ success: false, error: err.message }, true); }
    }
  );

  server.tool(
    'po_price_history',
    'Get tick-level price history for an asset over a time range.',
    {
      asset: z.string().describe('Asset symbol'),
      from_timestamp: z.coerce.number().describe('Start unix timestamp (seconds)'),
      to_timestamp: z.coerce.number().describe('End unix timestamp (seconds)'),
      limit: z.coerce.number().min(1).max(5000).optional().default(500),
    },
    async ({ asset, from_timestamp, to_timestamp, limit }) => {
      try { return jsonResult(core.getPriceHistory(asset, from_timestamp, to_timestamp, limit)); }
      catch (err) { return jsonResult({ success: false, error: err.message }, true); }
    }
  );

  server.tool(
    'po_indicators',
    'Get the latest calculated indicators for an asset (MA1/2/3, RSI, Bollinger Bands, Stochastic, Keltner, Schaff).',
    {
      asset: z.string().describe('Asset symbol'),
      limit: z.coerce.number().min(1).max(200).optional().default(1).describe('Number of indicator rows to return (default 1 = latest)'),
    },
    async ({ asset, limit }) => {
      try { return jsonResult(core.getIndicators(asset, limit)); }
      catch (err) { return jsonResult({ success: false, error: err.message }, true); }
    }
  );

  server.tool(
    'po_signals',
    'Get recent trading signals (CALL/PUT) generated by the bot\'s KT strategy pipeline.',
    {
      asset: z.string().optional().describe('Filter by asset (omit for all assets)'),
      limit: z.coerce.number().min(1).max(200).optional().default(20),
      direction: z.enum(['CALL', 'PUT']).optional().describe('Filter by direction'),
    },
    async ({ asset, limit, direction }) => {
      try { return jsonResult(core.getSignals(asset || null, limit, direction || null)); }
      catch (err) { return jsonResult({ success: false, error: err.message }, true); }
    }
  );

  server.tool(
    'po_tracked_assets',
    'List all assets that the bot has received candle data for, with candle counts and latest timestamp.',
    {},
    async () => {
      try { return jsonResult(core.listTrackedAssets()); }
      catch (err) { return jsonResult({ success: false, error: err.message }, true); }
    }
  );
}
